export const roles = {
  STUDENT: "STUDENT",
  MARKETING_COORDINATOR: "MARKETING COORDINATOR",
  MARKETING_MANAGER: "MARKETING MANAGER",
  ADMIN: "Admin",
  ALL: ["STUDENT", "MARKETING COORDINATOR", "MARKETING MANAGER", "Admin"]
};
